### ISSUE TITLE
Explicit GCS support in addition to 'S3 Compatible'.

### ISSUE THREAD

**Issue by rbtcollins** [jenkinsci/jobcacher-plugin#137]
### What feature do you want to see added?

I'd love it if (perhaps layering on google-storage-plugin) this plugin could be used to store a cache on GCS.

I'm trying to use jobcacher with Googles interoperability feature (https://cloud.google.com/storage/docs/interoperability), which requires an HMAC keypair https://cloud.google.com/storage/docs/authentication/managing-hmackeys#create and then a custom endpoint for the client, which I've configured up... but am getting a 400 bad request on attempts to read from the cache. It seems likely that this is a missing verb or some such, and using something GCS aware would be easier.

**Comment by repolevedavaj** [comment]
@rbtcollins thanks for you suggestion. I am not really familiar with GCS and its interoperability feature so I would have to take a deeper look. Is there any drawback if using the interoperability feature (e.g. performance) that could be a reason to introduce native support?

**Comment by rbtcollins** [comment]
If the S3 code can be made to work with the compatibility feature, I don't see any drawbacks. Right now I don't even know what exact request the cache code is making to facilitate troubleshooting the cause for the 400.

**Comment by repolevedavaj** [comment]
OK I will take a look and let you know

**Comment by rbtcollins** [comment]
I'm going to guess that this is the same issue the jenkins-pipeline-cache plugin had - see the linked ticket there and the PRs that fix it.

**Comment by repolevedavaj** [comment]
@rbtcollins I just did some tests and in my case it worked with only specifying credentials, endpoint and bucket name. What settings are you using?

**Comment by rbtcollins** [comment]
```
      globalItemStorage:
        storage:
          nonAWSS3:
            bucketName: ${JOBCACHER_BUCKET}
            credentialsId: jobcacher-hmac-keys
            endpoint: https://storage.googleapis.com
            parallelDownloads: false
            pathStyleAccess: false
            region: EUROPE-WEST1
            signerVersion: AWS4SignerType
```
