### ISSUE TITLE
No jenkins.plugins.itemstorage.ItemStorage implementation found for nonAWSS3

### ISSUE THREAD

**Issue by pavlo-bondarenko** [jenkinsci/jobcacher-plugin#223]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Plugin version 399.v12d4fa_dd3db_d
  Jenkins version 2.401.3
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins running in Kubernetes via https://charts.jenkins.io/jenkins, chart version 4.3.23

### Reproduction steps

1. Install plugin
2. Go to <jenkins-url>/manage/configure → Storage implementation → Jenkins controller is only available option in dropdown list
3. Add configuration:
```
                unclassified:
                  ...
                  globalItemStorage:
                    storage:
                      nonAWSS3:
                        bucketName: jenkins-job-cacher
                        credentialsId: job-cacher-hmac-key
                        endpoint: https://storage.googleapis.com
                        parallelDownloads: false
                        pathStyleAccess: false
```
4. Check Jenkins logs, notice `No jenkins.plugins.itemstorage.ItemStorage implementation found for nonAWSS3`

### Expected Results

S3 and nonAWSS3 are configurable storage implementations for plugin

### Actual Results

- Jenkins controller is only available option in dropdown list for Storage implementation
- `No jenkins.plugins.itemstorage.ItemStorage implementation found for nonAWSS3`
